/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordleRouteImport } from './routes/wordle'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as IndexRouteImport } from './routes/index'

const WordleRoute = WordleRouteImport.update({
  id: '/wordle',
  path: '/wordle',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/timeline': typeof TimelineRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/timeline': typeof TimelineRoute
  '/wordle': typeof WordleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/messages': typeof MessagesRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/timeline': typeof TimelineRoute
  '/wordle': typeof WordleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/messages' | '/signup' | '/social' | '/timeline' | '/wordle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/messages' | '/signup' | '/social' | '/timeline' | '/wordle'
  id:
    | '__root__'
    | '/'
    | '/messages'
    | '/signup'
    | '/social'
    | '/timeline'
    | '/wordle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MessagesRoute: typeof MessagesRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  TimelineRoute: typeof TimelineRoute
  WordleRoute: typeof WordleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wordle': {
      id: '/wordle'
      path: '/wordle'
      fullPath: '/wordle'
      preLoaderRoute: typeof WordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MessagesRoute: MessagesRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  TimelineRoute: TimelineRoute,
  WordleRoute: WordleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
